import React, { useEffect, useState } from "react";
import useMLScheduleStore from "../../stores/useMLScheduleStore";

const STATUS_BADGES = {
  draft: { bg: "bg-gray-100", text: "text-gray-700", label: "Draft" },
  confirmed: { bg: "bg-green-100", text: "text-green-700", label: "Confirmed" },
  completed: { bg: "bg-blue-100", text: "text-blue-700", label: "Completed" },
  cancelled: { bg: "bg-red-100", text: "text-red-700", label: "Cancelled" },
};

const MLScheduleHistory = () => {
  const {
    schedules,
    loading,
    error,
    fetchSchedules,
    fetchScheduleById,
    currentSchedule,
    clearCurrentSchedule,
  } = useMLScheduleStore();

  const [statusFilter, setStatusFilter] = useState("");
  const [viewingId, setViewingId] = useState(null);

  useEffect(() => {
    fetchSchedules({ status: statusFilter || undefined });
  }, [statusFilter]);

  const handleView = async (id) => {
    setViewingId(id);
    await fetchScheduleById(id);
  };

  const handleBack = () => {
    setViewingId(null);
    clearCurrentSchedule();
  };

  // Detail view
  if (viewingId && currentSchedule) {
    const badge = STATUS_BADGES[currentSchedule.status] || STATUS_BADGES.draft;
    return (
      <div className="space-y-6">
        <button
          onClick={handleBack}
          className="flex items-center gap-2 text-sm text-primary/60 hover:text-primary transition"
        >
          <span>←</span> Back to History
        </button>

        <div className="bg-white rounded-2xl border border-primary/10 p-5">
          <div className="flex flex-wrap items-center gap-3 mb-4">
            <h2 className="text-xl font-bold text-primary">
              {currentSchedule.dayName}, {new Date(currentSchedule.date).toLocaleDateString("en-US", {
                year: "numeric", month: "long", day: "numeric"
              })}
            </h2>
            <span className={`px-2.5 py-0.5 rounded-full text-xs font-semibold ${badge.bg} ${badge.text}`}>
              {badge.label}
            </span>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
            <div className="text-center p-3 rounded-xl bg-gray-50">
              <p className="text-lg font-bold text-primary">
                {currentSchedule.totalPredictedWasteKg?.toLocaleString()} kg
              </p>
              <p className="text-xs text-primary/50">Total Predicted</p>
            </div>
            <div className="text-center p-3 rounded-xl bg-green-50">
              <p className="text-lg font-bold text-green-700">{currentSchedule.summary?.dispatched || 0}</p>
              <p className="text-xs text-green-600/70">Dispatched</p>
            </div>
            <div className="text-center p-3 rounded-xl bg-gray-50">
              <p className="text-lg font-bold text-gray-500">{currentSchedule.summary?.skipped || 0}</p>
              <p className="text-xs text-gray-500/70">Skipped</p>
            </div>
            <div className="text-center p-3 rounded-xl bg-blue-50">
              <p className="text-lg font-bold text-blue-700">{currentSchedule.summary?.totalTrucksAssigned || 0}</p>
              <p className="text-xs text-blue-600/70">Trucks</p>
            </div>
          </div>

          {currentSchedule.generatedBy && (
            <p className="text-xs text-primary/40 mb-1">
              Generated by: {currentSchedule.generatedBy.name || currentSchedule.generatedBy.email}
            </p>
          )}
          {currentSchedule.confirmedBy && (
            <p className="text-xs text-primary/40">
              Confirmed by: {currentSchedule.confirmedBy.name || currentSchedule.confirmedBy.email}
              {currentSchedule.confirmedAt && (
                <span> at {new Date(currentSchedule.confirmedAt).toLocaleString()}</span>
              )}
            </p>
          )}
        </div>

        {/* Area breakdown */}
        <div className="bg-white rounded-2xl border border-primary/10 overflow-hidden">
          <div className="px-5 py-3 border-b border-primary/10">
            <h3 className="font-semibold text-primary">Area Breakdown</h3>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 text-left">
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Area</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Type</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Predicted</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Category</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Action</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Trucks</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-primary/5">
                {currentSchedule.areas?.map((d) => {
                  const catBadge = STATUS_BADGES[d.wasteCategory] ||
                    { bg: "bg-gray-100", text: "text-gray-700" };
                  return (
                    <tr key={d.area} className={d.action === "skip" ? "opacity-50" : ""}>
                      <td className="px-5 py-3 font-medium text-primary">
                        {d.area}
                        {d.isHoliday && <span className="ml-1.5">🎉</span>}
                      </td>
                      <td className="px-5 py-3 text-primary/60">{d.areaType}</td>
                      <td className="px-5 py-3 font-semibold text-primary">
                        {d.predictedWasteKg?.toLocaleString()} kg
                      </td>
                      <td className="px-5 py-3">
                        <span className={`px-2 py-0.5 rounded-full text-xs font-medium
                          ${d.wasteCategory === "critical" ? "bg-red-100 text-red-700" :
                            d.wasteCategory === "high" ? "bg-orange-100 text-orange-700" :
                            d.wasteCategory === "medium" ? "bg-amber-100 text-amber-700" :
                            d.wasteCategory === "low" ? "bg-green-100 text-green-700" :
                            "bg-gray-100 text-gray-600"}`}>
                          {d.wasteCategory}
                        </span>
                      </td>
                      <td className="px-5 py-3">
                        <span className={`px-2 py-0.5 rounded-full text-xs font-medium
                          ${d.action === "dispatch" ? "bg-green-100 text-green-700" :
                            d.action === "reduced" ? "bg-amber-100 text-amber-700" :
                            "bg-gray-100 text-gray-500"}`}>
                          {d.action}
                        </span>
                      </td>
                      <td className="px-5 py-3 text-primary/60">
                        {d.assignedTrucks?.map((t) => t.licensePlate || t.truckId).join(", ") || "—"}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    );
  }

  // List view
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-primary tracking-tight">
            Schedule History
          </h1>
          <p className="text-sm text-primary/60 mt-1">
            Past ML-generated waste collection schedules
          </p>
        </div>

        {/* Filter */}
        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          className="px-4 py-2 rounded-xl border border-primary/15 text-sm
                     focus:outline-none focus:ring-2 focus:ring-accent/30
                     text-primary"
        >
          <option value="">All Statuses</option>
          <option value="draft">Draft</option>
          <option value="confirmed">Confirmed</option>
          <option value="completed">Completed</option>
          <option value="cancelled">Cancelled</option>
        </select>
      </div>

      {/* Error */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-xl p-4">
          <p className="text-sm text-red-700">{error}</p>
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="text-center py-12">
          <svg className="animate-spin h-8 w-8 mx-auto text-accent" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          <p className="text-sm text-primary/50 mt-3">Loading schedules...</p>
        </div>
      )}

      {/* Schedule List */}
      {!loading && schedules.length > 0 && (
        <div className="bg-white rounded-2xl border border-primary/10 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 text-left">
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Date</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Day</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Total Waste</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Dispatched</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Trucks</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Status</th>
                  <th className="px-5 py-3 text-xs font-semibold text-primary/50 uppercase">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-primary/5">
                {schedules.map((s) => {
                  const badge = STATUS_BADGES[s.status] || STATUS_BADGES.draft;
                  return (
                    <tr key={s._id} className="hover:bg-gray-50/50 transition">
                      <td className="px-5 py-3 font-medium text-primary">
                        {new Date(s.date).toLocaleDateString("en-US", {
                          year: "numeric", month: "short", day: "numeric"
                        })}
                      </td>
                      <td className="px-5 py-3 text-primary/60">{s.dayName}</td>
                      <td className="px-5 py-3 font-semibold text-primary">
                        {s.totalPredictedWasteKg?.toLocaleString()} kg
                      </td>
                      <td className="px-5 py-3 text-primary/70">
                        {s.summary?.dispatched || 0} / {s.summary?.totalAreas || 10}
                      </td>
                      <td className="px-5 py-3 text-primary/70">
                        {s.summary?.totalTrucksAssigned || 0}
                      </td>
                      <td className="px-5 py-3">
                        <span className={`px-2.5 py-0.5 rounded-full text-xs font-semibold ${badge.bg} ${badge.text}`}>
                          {badge.label}
                        </span>
                      </td>
                      <td className="px-5 py-3">
                        <button
                          onClick={() => handleView(s._id)}
                          className="text-xs font-medium text-accent hover:underline"
                        >
                          View Details
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Empty State */}
      {!loading && schedules.length === 0 && (
        <div className="text-center py-16">
          <p className="text-5xl mb-4">📋</p>
          <h3 className="text-lg font-semibold text-primary/70 mb-2">
            No Schedules Found
          </h3>
          <p className="text-sm text-primary/50">
            {statusFilter
              ? `No schedules with status "${statusFilter}". Try a different filter.`
              : "Generate your first ML schedule from the ML Schedule page."}
          </p>
        </div>
      )}
    </div>
  );
};

export default MLScheduleHistory;
